### ISSUE TITLE
[REFACT] 논의가 필요한 리팩토링

### ISSUE THREAD

**Issue by thguss** [Team-Smeme/Smeme-server-renewal#159]
## What is this issue? 🚀
- **`안건1.` Member.diaryComboCount 칼럼 추가**
  - 비효율적인 쿼리 호출: 일기 작성의 연속 개수를 알기 위해서만 쿼리를 최대 50개 호출 (후에 100개로도 늘어날 가능성, 성능 개선 필요)
  - 일기를 작성한 시점으로부터 하루 전에 작성한 일기가 있는가? => `diaryComboCount++` 없는가? => `diaryComboCount=0`
  - 업데이트 후 diaryComboCount 칼럼 하나만으로 뱃지 획득 여부 판단 가능
- **`안건2.` EntityService 내 EntityRepository만 호출**
  - 단일 책임 원칙: DiaryService에서는 Diary 엔티티 관리만 해야하는 것이 아닌가? 하는 생각이 들었음🤔
  - 중복되는 메서드를 줄일 수 있다! (Ex. Entity findById)
  - Entity 외에 다른 Repository가 필요하다면 해당 Service로 호출하는 것이 어떤지?
  - Ex. DiaryService 내에서 TopicRepository가 필요 => TopicService를 거쳐서 호출

## Progress 🏃‍♀️
- [ ] 안건1 논의
- [ ] 안건2 논의

**Comment by unanchoi** [comment]
`안건1`
너무 좋은 것 같습니다!

`안건2`
 해당 의견도 좋은 것 같습니다! 추가적으로 고려해볼 수 있는 방법이 있을 것 같아 의견 남겨봅니다.

`Facade Pattern` 적용. 말씀하신 것 처럼, Service에서는 Service 계층에 해당하는 Repository만 호출하게 리팩토링 한 후에  Controller와 Service 계층사이에 Facade 계층을 넣어, Facade에서 Service의 의존성을 주입하는 형태도 좋은 것 같습니다! 결국 비슷한 결과로 리팩토링을 진행하는 방향이지만, Service 계층 끼리의 의존도를 낮출 수 있기 때문에 고려해볼 수 있는 방향인 것 같습니다!
다만 단점은 리팩토링시에 공수가 조금 더 들 것 같은점 인것 같습니다!

**Comment by unanchoi** [comment]
추가적으로 현재 Service에서 repository를 호출하고 있기 때문에,
예를 들어 member를 조회해야하는 service가 2개 있는 경우 (TopicService, DiaryService)
각각에 Service에서 아래 코드처럼 private method인 `getMemberById()` method를 만들어 조회하고 있습니다!

```Java
        private Member getMember(Long memberId) {
                return memberRepository.findById(memberId)
                        .orElseThrow(() -> new EntityNotFoundException(INVALID_MEMBER.getMessage()));
        }


        private Badge getBadge(Long id) {
                return badgeRepository.findById(id)
                        .orElseThrow(() -> new EntityNotFoundException(INVALID_BADGE.getMessage()));
```

실제로 해당 method를 만들지 않으면, DiaryService내에서 member를 조회해야 할 일이 여러번 있을 때, 해당 상황마다 아래 코드가 추가되어야 하기 때문에 각각의 서비스에서 중복되는 코드가 존재하는 것으로 알고 있습니다! 

```Java
memberRepository.findById().orElseThrow(() -> new EntityNotFoundException());
```

따라서 `안건2`와 같은 경우에는 Service를 조회하기 때문에 이부분에서 더 좋을 것 같습니다~! 
```Java
private Member getMember(Long memberId) {
                return memberRepository.findById(memberId)
                        .orElseThrow(() -> new EntityNotFoundException(INVALID_MEMBER.getMessage()));
        }
```
해당 방향으로 리팩토링 할 시에는 위와 같이 사용하는 method는 의존하는 Service 계층에서 사용될 것 같은데, 적절한 접근제어자 (protected나 default)를 적용하는 것이 좋을 것 같아요!

그리고 이거 적으면서 찾았는데, Service마다 `getMember`, `getMemberById`로 역할은 같은데 사용하는 method 명이 다른 것 같은데 이것도 통일하면 좋겠네요!

**Comment by thguss** [comment]
안건2에 대한 구체적인 예시와 함께 제안해주셔서 감사해요! 너무 좋은 것 같습니다~!
접근 제어자 설정, 메서드명 통일 방식에도 매우 공감합니다 :)
코어타임 때 구체적으로 논의해보고 방향 결정해서 리팩토링 진행해보아요~!
