### ISSUE TITLE
리팩토링 하면서 생긴 논의 포인트 정리

### ISSUE THREAD

**Issue by unanchoi** [Team-Smeme/Smeme-server-renewal#166]
## What is this issue? 🚀
1. protected로 접근 제어자를 설정하니 따로 패키징을 하고 있는 AuthService에서는 사용할 수 없어서, 필요한 method는 제어자를 default 혹은 public으로 바꿔야 할 것 같습니다!!
아니면 auth 패키지를 삭제하고 service 패키지에서 모두 관리하는 방법도 있을 것 같습니다.

2. service에서 return하는 method들에 대한 구분이 필요한 것 같아요...! 이건 제가 생각 못했던 부분인데 ..
예를들어 `MemberService`에서 유저정보를 return 해주는 메소드가 필요하다고 가정했을 때
```Java
 protected Member get(Long id) {
        return memberRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(INVALID_MEMBER.getMessage()));
    }
```
이렇게 id로 repository에서 member를 조회하는 method를 하나 있는 상황에서 아래처럼 추가로 id로 member를 조회해서 response dto로 바꾼후에 return 해주는 service method가 필요한 경우에 애매해지는 상황이 발생하네요!
PR은 getInfo()로 네이밍을 바꿔서.. 올렸는데 어떻게 하면 좋을지 의논해보면 좋을 것 같습니다!

```Java
public MemberGetResponseDTO get(Long memberId) {
        Member member = get(memberId);
        GoalResponseDTO goal = goalService.getByType(member.getGoal());
        List<TrainingTime> trainingTimeList = trainingTimeService.getAllByMemberId(memberId);

        // 기본 시간 설정
        if (trainingTimeService.getAllByMemberId(memberId).isEmpty()) {
            TrainingTimeResponseDTO trainingTimeResponseDTO = TrainingTimeResponseDTO.builder()
                    .day("")
                    .hour(22)
                    .minute(0)
                    .build();
            return MemberGetResponseDTO.of(goal, member, trainingTimeResponseDTO, BadgeResponseDTO.of(memberBadgeService.getBadgeByMemberId(memberId)));
        }

        TrainingTime trainingTime = getOneTrainingTime(trainingTimeList);
        TrainingTimeResponseDTO trainingTimeResponseDTO = TrainingTimeResponseDTO.builder()
                .day(getDays(trainingTimeList))
                .hour(trainingTime.getHour())
                .minute(trainingTime.getMinute())
                .build();
        return MemberGetResponseDTO.of(goal, member, trainingTimeResponseDTO, BadgeResponseDTO.of(memberBadgeService.getBadgeByMemberId(memberId)));
    }
```

## Progress 🏃‍♀️
- [ ]

**Comment by thguss** [comment]
1. AuthService 문제가 있었군요? 그렇다면 AuthService의 패키지를 풀었을 때 관리가 힘들지 않다면 전자의 방식으로, 관리가 조금이라도 복잡해질 것 같다면 후자의 public 방식으로 진행하면 좋을 것 같아요!

**Comment by thguss** [comment]
2. 아래의 get은 회원 프로필을 가져오는 메소드가 맞을까요?? 그렇다면 아래 쪽 메소드를 `getInfo` 또는 `getProfile`이라고 명명해주는 것이 더 직관적일 것이라고 생각해요. 왜냐하면 Member get(id) 메소드는 Entity 자체를 가져오는 것이고, 아래 메소드는 회원 데이터를 가공해서 가져오는 것이니 메소드를 다르게 해야한다면 아래 쪽 메소드를 좀 더 구체적인 메소드명으로 가져가도 좋을 것 같다고 생각합니다!

**Comment by unanchoi** [comment]
확인했습니다!~ 관련해서 다시 리팩토링하고 리뷰 요청하겠습니다~ 감사합니다
