### ISSUE TITLE
[FIX]Exception 의존성 문제

### ISSUE THREAD

**Issue by unanchoi** [Team-Smeme/Smeme-server-renewal#77]
아래 부분에서, `NotFoundException`이 `org.webjars` 해당 라이브러리에서 import 해서 사용하고 있습니다.

https://github.com/Team-Smeme/Smeme-server-renewal/blob/afa3150aa846dce79401dfe356190199540d7e9d/src/main/java/com/smeme/server/service/DiaryService.java#L81

Swagger, RestDocs 관련 설정을 하던 중에 해당 Exception이랑  새로 설정한 의존성이 맞지 않아 Application 실행이 안됩니다. ㅠ
`IllegalArgumentException`을 상속받아 CustomException을 구현하거나, 다른 Exception을 사용하는 것이 어떨지 논의가 필요할 것 같습니다!

**Comment by thguss** [comment]
> 아래 부분에서, `NotFoundException`이 `org.webjars` 해당 라이브러리에서 import 해서 사용하고 있습니다.
> 
> https://github.com/Team-Smeme/Smeme-server-renewal/blob/afa3150aa846dce79401dfe356190199540d7e9d/src/main/java/com/smeme/server/service/DiaryService.java#L81
> 
> Swagger, RestDocs 관련 설정을 하던 중에 해당 Exception이랑  새로 설정한 의존성이 맞지 않아 Application 실행이 안됩니다. ㅠ
> `IllegalArgumentException`을 상속받아 CustomException을 구현하거나, 다른 Exception을 사용하는 것이 어떨지 논의가 필요할 것 같습니다!

좋습니다! 다른 예외 찾아보고 마땅치 않으면 custom하도록 하겠습니다 :)
